### ISSUE TITLE
Error building in Netrunner

### ISSUE THREAD

**Issue by edo0** [jeffgreenca/laughr#4]
Dear Jeff,
First of all thank you for this tool, it is exactly what I was needing to manage to rip away those very terrible sound effects which have been plaguing comedy (especially unfunny comedy, but some nice shows too) since a few decades.
That said, I was trying to build the software on my machine, and I go the error you can find below.
My OS is Netrunner, based on the latest Manjaro (Arch derivative) , with Python 3.8
Being a newbie, I suspect this is the result of a mistake of mine.
I would be really happy if you could give me a hint as to the right way of solving it.
Thank you and best wishes of a Happy New Year!
ed

 sudo pipenv install   
 [sudo] password for user:  
 Creating a virtualenv for this project… 
 Pipfile: /home/user/laughr/src/Pipfile 
 Using /usr/bin/python (3.8.1) to create virtualenv… 
 ⠦ Creating virtual environment...Already using interpreter /usr/bin/python 
 Using base prefix '/usr'                                                                                                                  
 New python executable in /root/.local/share/virtualenvs/src-uzc96BV4/bin/python                                                           
 Installing setuptools, pip, wheel...                                                                                                      
 done.                                                                                                                                     

 ✔ Successfully created virtual environment!  
 Virtualenv location: /root/.local/share/virtualenvs/src-uzc96BV4 
 Pipfile.lock not found, creating… 
 Locking [dev-packages] dependencies… 
 Locking [packages] dependencies… 
 ✘ Locking Failed!  
 Traceback (most recent call last): 
   File "/usr/lib/python3.8/site-packages/pipenv/resolver.py", line 126, in <module>
     main() 
   File "/usr/lib/python3.8/site-packages/pipenv/resolver.py", line 118, in main 
     _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, 
   File "/usr/lib/python3.8/site-packages/pipenv/resolver.py", line 78, in _main 
     results = resolve( 
   File "/usr/lib/python3.8/site-packages/pipenv/resolver.py", line 61, in resolve 
     return resolve_deps( 
   File "/usr/lib/python3.8/site-packages/pipenv/utils.py", line 718, in resolve_deps 
     resolved_tree, hashes, markers_lookup, resolver = actually_resolve_deps( 
   File "/usr/lib/python3.8/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps 
     resolved_tree = resolver.resolve()
   File "/usr/lib/python3.8/site-packages/pipenv/utils.py", line 385, in resolve
     results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
   File "/usr/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
     has_changed, best_matches = self._resolve_one_round()
   File "/usr/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 206, in  _resolve_one_round
     for dep in self._iter_dependencies(best_match):
   File "/usr/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 301, in  _iter_dependencies
     dependencies = self.repository.get_dependencies(ireq)
   File "/usr/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in  get_dependencies
     legacy_results = self.get_legacy_dependencies(ireq)
   File "/usr/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in  get_legacy_dependencies
     results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
   File "/usr/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in  resolve_reqs
     results = resolver._resolve_one(reqset, ireq)
   File "/usr/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 260, in  _resolve_one
     abstract_dist = self._get_abstract_dist_for(req_to_install)
   File "/usr/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 211, in  _get_abstract_dist_for 
     abstract_dist = self.preparer.prepare_linked_requirement(
   File "/usr/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py",  line 294, in prepare_linked_requirement
     abstract_dist.prep_for_dist(finder, self.build_isolation)
   File "/usr/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py",  line 127, in prep_for_dist
     self.req.run_egg_info()
   File "/usr/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line  470, in run_egg_info
     call_subprocess(
   File "/usr/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 703, in  call_subprocess
     raise InstallationError( 
 pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info"  failed with error code 1 in /tmp/tmp2d1tvj9sbuild/functools32/
 File "/usr/lib/python3.8/site-packages/pipenv/resolver.py", line 126, in <module>
     main()
   File "/usr/lib/python3.8/site-packages/pipenv/resolver.py", line 118, in main
     _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system,
   File "/usr/lib/python3.8/site-packages/pipenv/resolver.py", line 78, in _main
     results = resolve(
   File "/usr/lib/python3.8/site-packages/pipenv/resolver.py", line 61, in resolve
     return resolve_deps(
   File "/usr/lib/python3.8/site-packages/pipenv/utils.py", line 718, in resolve_deps
     resolved_tree, hashes, markers_lookup, resolver = actually_resolve_deps(
   File "/usr/lib/python3.8/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
     resolved_tree = resolver.resolve()
   File "/usr/lib/python3.8/site-packages/pipenv/utils.py", line 385, in resolve
     results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
   File "/usr/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
     has_changed, best_matches = self._resolve_one_round()
   File "/usr/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 206, in  _resolve_one_round
     for dep in self._iter_dependencies(best_match):
   File "/usr/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 301, in  _iter_dependencies
     dependencies = self.repository.get_dependencies(ireq)
   File "/usr/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in  get_dependencies
     legacy_results = self.get_legacy_dependencies(ireq)
   File "/usr/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in  get_legacy_dependencies
     results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
   File "/usr/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in  resolve_reqs
     results = resolver._resolve_one(reqset, ireq)
   File "/usr/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 260, in  _resolve_one
     abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 211, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "/usr/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "/usr/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 470, in run_egg_info
    call_subprocess(
  File "/usr/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 703, in call_subprocess
    raise InstallationError(
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmp2d1tvj9sbuild/functools32/

**Comment by jeffg-dev** [comment]
Python 3.8 isn't supported by pipenv, according to this - https://github.com/pypa/pipenv/issues/3468

**Comment by edo0** [comment]
Dear jeff, 
sorry to bother you again. After failing to get the environment working, I would like to ask you for the setup you ran this programme on, so that I can try to replicate it in Virtualbox.
Thank you in advance!
